const ActionTypes = {

    // Register User Constant 
    GET_REGISTER_USER_PROFILE: "GET_REGISTER_USER_PROFILE",
    GET_REGISTER_USER_PROFILE_LOADING: "GET_REGISTER_USER_PROFILE_LOADING",
    GET_REGISTER_USER_PROFILE_ERROR: "GET_REGISTER_USER_PROFILE_ERROR",
};

export default ActionTypes;